
import React, {useState, useEffect} from 'react';
import axios from 'axios';
import {connect} from 'react-redux';
import { Redirect, Route, Switch } from 'react-router';

import './App.css';
import MyCard from './components/BusinessCard';
import MyHeader from './components/Header';
import AddBusinessCard from './components/AddBusinessCard';

const App = ({token}) => {

  const [allCards, setCards] = useState([]);

	useEffect(()=> {
		axios.post('http://localhost:5000/getAllCards', {'username': 'John'})
      .then(res => {
        setCards(res.data);
      })
      .catch(err => {
    console.log("Error getting all cards", err)
      });
	},[])

  if (!token) {
		return <Redirect push to ="login" />
	}
  // We are displaying first our own card then all business cards that belong to us
  // We're using the _id generated by mongo for the key of the map
  return (
    <div className="App">
      <MyHeader />
      <Switch>
        <Route exact path="/add" component={AddBusinessCard}/>
        <Route path="/" >
          <h1 className="my-4">My own Business cards</h1>
          <MyCard user={token.user}/>
          <div className="mt-5">
            <h5>List of cards</h5>
            {(allCards && allCards.length > 0) 
            ? allCards.map(card => <MyCard key={card._id} user={card}/>)
            : <p>No cards available</p>
            }
          </div>
        </Route>
      </Switch>
    </div>
  );
}

const getProps = state => {
  return {
    token  : state.access_token
  }
}
export default connect(getProps, null)(App);
